=== Eric-Lachcik/PR1/act35/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "Nombre": {
                "type": "string"
            },
            "dulzura": {
                "type": "integer",
                "minimum": 0,
                "maximum": 10
            },
            "Disponible": {
                "type": "boolean"
            },
            "Imagen": {
                "type": "string",
                "format": "uri"
            }
        },
        "required": ["Nombre", "dulzura", "Disponible", "Imagen"]
    }
}

=== Eric-Lachcik/PR1/act35/gatitos.json
[
    {
        "Nombre": "Gato Persa",
        "dulzura": 8,
        "Disponible": true,
        "Imagen": "https://nupec.com/wp-content/uploads/2022/02/persian-cat-2021-08-26-17-35-23-utc.jpg"
    },
    {
        "Nombre": "Gato Azul Ruso",
        "dulzura": 7,
        "Disponible": false,
        "Imagen": "https://nupec.com/wp-content/uploads/2022/02/russian-blue-cat-2021-08-26-22-38-47-utc.jpg"
    },
    {
        "Nombre": "Gato Maine Coon",
        "dulzura": 10,
        "Disponible": true,
        "Imagen": "https://nupec.com/wp-content/uploads/2022/02/cute-maine-coon-cat-2021-08-26-16-15-59-utc.jpg"
    },
    {
        "Nombre": "Gato RagDoll",
        "dulzura": 9,
        "Disponible": true,
        "Imagen": "https://nupec.com/wp-content/uploads/2022/02/ragdoll-cat-portrait-with-beautiful-blue-eyes-2022-02-13-18-49-19-utc.jpg"
    },
    {
        "Nombre": "Gato Angora",
        "dulzura": 10,
        "Disponible": true,
        "Imagen": "https://nupec.com/wp-content/uploads/2022/02/blue-eyes-birman-cat-2021-08-29-22-43-33-utc.jpg"
    },
    {
        "Nombre": "Gato Naranja",
        "dulzura": 10,
        "Disponible": true,
        "Imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-04CO5pUxmf20pbO2OF3GnOVFn49je4SSYQ&s"
    }
]
